/** Browser-safe constants for tool execution contract validation. */

export type ApprovalCategory =
  | 'NO_APPROVAL_REQUIRED'
  | 'HUMAN_REVIEW_REQUIRED'
  | 'EXPLICIT_APPROVAL_REQUIRED'
  | 'SAFETY_CRITICAL_APPROVAL_REQUIRED'
  | 'FINAL_ARTIFACT_APPROVAL_REQUIRED';

export const APPROVAL_CATEGORIES: readonly ApprovalCategory[] = [
  'NO_APPROVAL_REQUIRED',
  'HUMAN_REVIEW_REQUIRED',
  'EXPLICIT_APPROVAL_REQUIRED',
  'SAFETY_CRITICAL_APPROVAL_REQUIRED',
  'FINAL_ARTIFACT_APPROVAL_REQUIRED',
];

export const MAX_CONTRACT_ID_LENGTH = 128;
export const MAX_TOOL_NAME_LENGTH = 128;
export const MAX_IDEMPOTENCY_KEY_LENGTH = 256;
export const MAX_CONTRACT_ARTIFACTS = 100;
